Created initial steps for liquibase integration

diff --git a/.github/workflows/nvip_tests.yml b/.github/workflows/nvip_tests.yml
--- a/.github/workflows/nvip_tests.yml
+++ b/.github/workflows/nvip_tests.yml
@@ -23,52 +23,52 @@ env:
   PRODUCT_DETECTOR_MODEL: 'en-pos-perceptron.bin'
 
 jobs:
-  # Build Main Project
-  build-test-backend:
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout
-        uses: actions/checkout@v3
-        with:
-          lfs: 'true'
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: '17'
-          distribution: 'temurin'
+  # # Build Main Project
+  # build-test-backend:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         lfs: 'true'
+  #     - name: Set up JDK 17
+  #       uses: actions/setup-java@v3
+  #       with:
+  #         java-version: '17'
+  #         distribution: 'temurin'
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ env.AWS_REGION }}
 
-      # Grab large files form S3 bucket
-      - name: Pull file from S3 bucket
-        run: |
-          cd nvip_data/productnameextraction
-          aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .
+  #     # Grab large files form S3 bucket
+  #     - name: Pull file from S3 bucket
+  #       run: |
+  #         cd nvip_data/productnameextraction
+  #         aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .
 
-      # MySQL DB for tests that require connection
-      - name: Prepare MySQL Test DB
-        run: |
-          sudo /etc/init.d/mysql start
-          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
-          mysql -e 'SHOW DATABASES;' -uroot -proot
-          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
+  #     # MySQL DB for tests that require connection
+  #     - name: Prepare MySQL Test DB
+  #       run: |
+  #         sudo /etc/init.d/mysql start
+  #         mysql -e 'CREATE DATABASE nvip;' -uroot -proot
+  #         mysql -e 'SHOW DATABASES;' -uroot -proot
+  #         mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
 
-      - name: Test and Build Backend with Maven
-        run: |
-          mvn dependency:go-offline
-          mvn package
+  #     - name: Test and Build Backend with Maven
+  #       run: |
+  #         mvn dependency:go-offline
+  #         mvn package
 
-      # Test report for tests that fail/skip
-      - name: Publish Test Report
-        if: success() || failure()
-        uses: scacap/action-surefire-report@v1
-        with:
-          check_name: Backend Test Report
+  #     # Test report for tests that fail/skip
+  #     - name: Publish Test Report
+  #       if: success() || failure()
+  #       uses: scacap/action-surefire-report@v1
+  #       with:
+  #         check_name: Backend Test Report
 
   # Build and Test Crawler Component
   build-test-crawler:
@@ -78,6 +78,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           lfs: 'true'
+
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
@@ -85,12 +86,30 @@ jobs:
           distribution: 'temurin'
 
       # Setup MySQL DB for tests that require connection (Might not need this)
-      - name: Prepare MySQL Test DB
-        run: |
-          sudo /etc/init.d/mysql start
-          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
-          mysql -e 'SHOW DATABASES;' -uroot -proot
-          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
+      - name: Start MySQL Service
+        run: sudo /etc/init.d/mysql start
+        # run: |
+        #   sudo /etc/init.d/mysql start
+        #   mysql -e 'CREATE DATABASE nvip;' -uroot -proot
+        #   mysql -e 'SHOW DATABASES;' -uroot -proot
+        #   mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
+
+      - name: Initialize DB
+        uses: liquibase-github-actions/update@v4.23.0
+        with:
+          changelogFile: "nvip_data/mysql-database/newDB/db.init.xml"
+
+          # The JDBC database connection URL
+          # string
+          # Required
+          url: ${{ env.HIKARI_URL }}
+
+          # The JDBC driver class
+          # string
+          # Optional
+          #driver: ""
+          password: ${{ env.HIKARI_PASSWORD }}
+          username: ${{ env.HIKARI_USER }}
 
       - name: Test and Build Crawler with Maven
         run: |
@@ -165,13 +184,31 @@ jobs:
           cd productnameextractor/nvip_data/data
           aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .
 
-      # Might not need this
-      - name: Prepare MySQL Test DB
-        run: |
-          sudo /etc/init.d/mysql start
-          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
-          mysql -e 'SHOW DATABASES;' -uroot -proot
-          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
+      # Setup MySQL DB for tests that require connection (Might not need this)
+      - name: Start MySQL Service
+        run: sudo /etc/init.d/mysql start
+        # run: |
+        #   sudo /etc/init.d/mysql start
+        #   mysql -e 'CREATE DATABASE nvip;' -uroot -proot
+        #   mysql -e 'SHOW DATABASES;' -uroot -proot
+        #   mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
+
+      - name: Initialize DB
+        uses: liquibase-github-actions/update@v4.23.0
+        with:
+          changelogFile: "nvip_data/mysql-database/newDB/db.init.xml"
+
+          # The JDBC database connection URL
+          # string
+          # Required
+          url: ${{ env.HIKARI_URL }}
+
+          # The JDBC driver class
+          # string
+          # Optional
+          #driver: ""
+          password: ${{ env.HIKARI_PASSWORD }}
+          username: ${{ env.HIKARI_USER }}
 
       - name: Test and Build Product Extractor with Maven
         run: |
@@ -206,19 +243,31 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      # Might not need this
-      - name: Prepare MySQL Test DB
-        run: |
-          sudo /etc/init.d/mysql start
-          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
-          mysql -e 'SHOW DATABASES;' -uroot -proot
-          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
+      # Setup MySQL DB for tests that require connection (Might not need this)
+      - name: Start MySQL Service
+        run: sudo /etc/init.d/mysql start
+        # run: |
+        #   sudo /etc/init.d/mysql start
+        #   mysql -e 'CREATE DATABASE nvip;' -uroot -proot
+        #   mysql -e 'SHOW DATABASES;' -uroot -proot
+        #   mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
 
-      - name: Test and Build Patchfinder with Maven
-        run: |
-          cd patchfinder
-          mvn dependency:go-offline
-          mvn package
+      - name: Initialize DB
+        uses: liquibase-github-actions/update@v4.23.0
+        with:
+          changelogFile: "nvip_data/mysql-database/newDB/db.init.xml"
+
+          # The JDBC database connection URL
+          # string
+          # Required
+          url: ${{ env.HIKARI_URL }}
+
+          # The JDBC driver class
+          # string
+          # Optional
+          #driver: ""
+          password: ${{ env.HIKARI_PASSWORD }}
+          username: ${{ env.HIKARI_USER }}
 
       - name: Publish Test Report
         if: success() || failure()
@@ -226,39 +275,39 @@ jobs:
         with:
           check_name: Patchfinder Test Report
 
-  # Deploy main backend project to container registry
-  deploy-backend:
-    runs-on: ubuntu-latest
-    needs: build-test-backend
-    if: ${{ success() && github.ref == 'refs/heads/dev' }}
-    steps:
-      - uses: actions/checkout@v3
+  # # Deploy main backend project to container registry
+  # deploy-backend:
+  #   runs-on: ubuntu-latest
+  #   needs: build-test-backend
+  #   if: ${{ success() && github.ref == 'refs/heads/dev' }}
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ env.AWS_REGION }}
 
-      # Pull large files so they're in the container
-      - name: Pull file from S3 bucket
-        run: |
-          cd productnameextractor/nvip_data/data
-          aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .  
+  #     # Pull large files so they're in the container
+  #     - name: Pull file from S3 bucket
+  #       run: |
+  #         cd productnameextractor/nvip_data/data
+  #         aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .  
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Login to GitHub Container Registry
+  #       uses: docker/login-action@v2
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
 
-      # Main project is called nvip-crawler, crawler component will be nvip-crawler-sub
-      - name: Build and Push Docker Image for Backend
-        run: |
-          docker build . -t nvip-crawler:dev -t ghcr.io/softwaredesignlab/nvip-crawler:dev
-          docker push ghcr.io/softwaredesignlab/nvip-crawler:dev
+  #     # Main project is called nvip-crawler, crawler component will be nvip-crawler-sub
+  #     - name: Build and Push Docker Image for Backend
+  #       run: |
+  #         docker build . -t nvip-crawler:dev -t ghcr.io/softwaredesignlab/nvip-crawler:dev
+  #         docker push ghcr.io/softwaredesignlab/nvip-crawler:dev
 
   # Deploy crawler component project to container registry
   deploy-crawler:
